name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 25
      uses: actions/setup-java@v1
      with:
        java-version: 25
    - name: Build with Maven
      run: mvn -B package --file pom.xml
